# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis 
#     https://github.com/eddelbuettel/r-travis/

sudo: required                                     

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libgsl0-dev r-cran-rcpp r-cran-mass
  - R --slave -e 'install.packages("RcppGSL", repo="http://ghrr.github.io/drat")'
  - ./travis-tool.sh install_r tweedie statmod

script: 
  - ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change


