// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// RtoAnovaCpp
Rcpp::List RtoAnovaCpp(const Rcpp::List& rparam, RcppGSL::Matrix& Y, RcppGSL::Matrix& X, RcppGSL::Matrix& isXvarIn, SEXP bIDsexp);
RcppExport SEXP mvabund_RtoAnovaCpp(SEXP rparamSEXP, SEXP YSEXP, SEXP XSEXP, SEXP isXvarInSEXP, SEXP bIDsexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rparam(rparamSEXP);
    Rcpp::traits::input_parameter< RcppGSL::Matrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< RcppGSL::Matrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< RcppGSL::Matrix& >::type isXvarIn(isXvarInSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bIDsexp(bIDsexpSEXP);
    __result = Rcpp::wrap(RtoAnovaCpp(rparam, Y, X, isXvarIn, bIDsexp));
    return __result;
END_RCPP
}
