# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RtoAnovaCpp <- function(rparam, Y, X, isXvarIn, bIDsexp) {
    .Call('mvabund_RtoAnovaCpp', PACKAGE = 'mvabund', rparam, Y, X, isXvarIn, bIDsexp)
}

